services:
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql
    environment:
      ACCEPT_EULA: '1'
      MSSQL_SA_PASSWORD: 'Root@1234'
    ports:
      - "1433:1433"
