version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    container_name: online-store-api
    ports:
      - "5000:80"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
    volumes:
      - ./Api:/app
